name: flutter_charts_gallery
description: A new Flutter project.

version: 1.0.0

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_echarts: ^1.0.6
  charts_flutter: ^0.5.0
  flutter_circular_chart: ^0.1.0
  flutter_charts: ^0.1.10
  fcharts: ^0.0.10
  syncfusion_flutter_charts: ^17.4.40

  # flutter_echarts
  number_display: ^2.1.4
  # charts_flutter
  cupertino_icons: ^0.1.0
  meta: ^1.1.1
  intl: ^0.15.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
